services:

    # Customer Profile
    nti.authorizenet.customer_profile:
        class: NTI\AuthorizeNetBundle\Services\Customer\ANetCustomerProfileService
        arguments: ["@service_container"]

    # Customer Payment Profile
    nti.authorizenet.customer_payment_profile:
        class: NTI\AuthorizeNetBundle\Services\Customer\ANetCustomerPaymentProfileService
        arguments: ["@service_container"]

    # Payment
    nti.authorizenet.payment_transaction:
        class: NTI\AuthorizeNetBundle\Services\Payment\ANetPaymentService
        arguments: ["@service_container"]

    # Transaction
    nti.authorizenet.payment_transaction_reporting:
        class: NTI\AuthorizeNetBundle\Services\Transaction\ANetTransactionReportingService
        arguments: ["@service_container"]
